###
POST http://localhost:8080/employee/get
Content-Type: application/json

{
  "id": 3
}

###
POST http://localhost:8080/employee/delete
Content-Type: application/json

{
  "id": 7
}

###
POST http://localhost:8080/employee/findAll
Content-Type: application/json

{
}