POST http://localhost:8080/job/save
Content-Type: application/json

{
  "name": "Java实习生",
  "remark": "实习培训"
}

###
POST http://localhost:8080/job/delete
Content-Type: application/json

{
  "id": 23
}

###
POST http://localhost:8080/job/update
Content-Type: application/json

{
  "id": "16",
  "name": "董事长",
  "remark": "董事长"
}

###
POST http://localhost:8080/job/get
Content-Type: application/json

{
  "id": 2
}

###
POST http://localhost:8080/job/findAll
Content-Type: application/json

{

}

###
POST http://localhost:8080/job/findExample
Content-Type: application/json

{
  "name": "Java"
}