POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "danny",
  "password": "123456"
}

###
POST http://localhost:8080/login?username=zhang&password=123456

###
POST http://localhost:8080/index

###
POST http://localhost:8080/employee/findExample
Content-Type: application/json

{
  "username": "zhang",
  "password": "123456"
}

###
POST http://localhost:8080/employee/get
Content-Type: application/json

{
  "id": 1
}

###
POST http://localhost:8080/findMenuTreeList
Content-Type: application/json
Cookie: Idea-95f9a482=571143fd-0d86-4e25-942b-5518fe0074f0; JSESSIONID=CAF191018FE01D27B7EAE8385FD1042A

{
}
