spring:
  application: 
    name: 'hrm-system'
  datasource:
    username: root
    password: 123456
    url: 'jdbc:mysql://localhost:3306/oa?serverTimezone=Asia/Shanghai'
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false  #关闭thymeleaf缓存

mybatis:
  type-aliases-package: org.design.model
  mapper-locations: 'classpath*:org/**/*Mapper.xml'
  ### 打印SQL语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true

 